name: bodFit_group5_summative
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


#-------------Packages start here------------#
dependencies:
  flutter:
    sdk: flutter

#-----------Utility packages--------#
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  
  #Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8


# State management
  get: ^4.6.5
  get_storage: ^2.1.1
#-------------------------./Packges End---------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true

  #---------Local Assests------#
  assets:
    # - assets/images/image1.jpg
    # - assets/images/exercise0.jpg
    # - assets/images/exercise1.jpg
    # - assets/images/exercise2.jpg
    # - assets/images/exercise3.jpg
    - assets/images/

  
  

  
  

  
  
  
  
  #-----Local Fonts-------#
  fonts:
    - family: Roboto
      fonts:
          - asset: assets\fonts\Roboto-Black.ttf
          - asset: assets\fonts\Roboto-Bold.ttf
          - asset: assets\fonts\Roboto-BoldItalic.ttf
          - asset: assets\fonts\Roboto-Italic.ttf
          - asset: assets\fonts\Roboto-Light.ttf
          - asset: assets\fonts\Roboto-LightItalic.ttf
          - asset: assets\fonts\Roboto-Medium.ttf
          - asset: assets\fonts\Roboto-MediumItalic.ttf
          - asset: assets\fonts\Roboto-Regular.ttf
          - asset: assets\fonts\Roboto-Thin.ttf
          - asset: assets\fonts\Roboto-ThinItalic.ttf
