// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24Fh2QDkeOoBfD14Oix5775rh713y97A',
    appId: '1:662759304121:web:bfdb667f9d8f2d3b486468',
    messagingSenderId: '662759304121',
    projectId: 'bodfit-6f6ce',
    authDomain: 'bodfit-6f6ce.firebaseapp.com',
    databaseURL: 'https://bodfit-6f6ce-default-rtdb.firebaseio.com',
    storageBucket: 'bodfit-6f6ce.appspot.com',
    measurementId: 'G-91TK4PWFM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3J_0ifEwAibD-LbdBmraU8DIKFgz24E',
    appId: '1:662759304121:android:4e56fbbeaa71003c486468',
    messagingSenderId: '662759304121',
    projectId: 'bodfit-6f6ce',
    databaseURL: 'https://bodfit-6f6ce-default-rtdb.firebaseio.com',
    storageBucket: 'bodfit-6f6ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBC6QaqZFaRxN_omVWF3JMA19pVLKW2VI',
    appId: '1:662759304121:ios:44aa949935c4ad79486468',
    messagingSenderId: '662759304121',
    projectId: 'bodfit-6f6ce',
    databaseURL: 'https://bodfit-6f6ce-default-rtdb.firebaseio.com',
    storageBucket: 'bodfit-6f6ce.appspot.com',
    androidClientId: '662759304121-k7j5i6udstdevispaolk3e9fqrqegl1o.apps.googleusercontent.com',
    iosClientId: '662759304121-s7gaoi2dn65t57l8niko0lpbbgt3uolv.apps.googleusercontent.com',
    iosBundleId: 'com.example.widgetAssignmnent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC24Fh2QDkeOoBfD14Oix5775rh713y97A',
    appId: '1:662759304121:web:6668dd3ac9d0cda9486468',
    messagingSenderId: '662759304121',
    projectId: 'bodfit-6f6ce',
    authDomain: 'bodfit-6f6ce.firebaseapp.com',
    databaseURL: 'https://bodfit-6f6ce-default-rtdb.firebaseio.com',
    storageBucket: 'bodfit-6f6ce.appspot.com',
    measurementId: 'G-E5SS0Z6SRX',
  );

}